STEAMGIFT_APPID: int = 753
CSGO_APPID: int = 730
TEAM_FORTRESS2_APPID: int = 440
DOTA2_APPID: int = 570

# CS:GO Временно не поддерживается
SUPPORTED_APPIDS: list[int] = [753, 440, 570]

# Фильтры
# TF2
# Качества
TF2_QUALITY_COLLECTORS: int = 263
TF2_QUALITY_DECORATED: int = 228
TF2_QUALITY_GENUINE: int = 107
TF2_QUALITY_HAUNTED: int = 231
TF2_QUALITY_SELFMADE: int = 348
TF2_QUALITY_STOCK: int = 274
TF2_QUALITY_STRANGE: int = 50
TF2_QUALITY_UNIQUE: int = 28
TF2_QUALITY_UNUSUAL: int = 232
TF2_QUALITY_VINTAGE: int = 40

# Типы
TF2_TYPE_ACTION: int = 51
TF2_TYPE_BUILDING: int = 220
TF2_TYPE_COSMETIC: int = 39
TF2_TYPE_CRAFT_ITEM: int = 42
TF2_TYPE_CRATE: int = 43
TF2_TYPE_FESTIVIZER: int = 285
TF2_TYPE_GIFT1: int = 106
TF2_TYPE_GIFT2: int = 252
TF2_TYPE_KILLSTREAK_KIT: int = 250
TF2_TYPE_MELEE: int = 44
TF2_TYPE_PACKAGE: int = 246
TF2_TYPE_PARTY_FAVOR: int = 29
TF2_TYPE_PRIMARY: int = 45
TF2_TYPE_PRIMARY_PDA: int = 233
TF2_TYPE_PROFESSIONAL_KILLSTREAK_KIT: int = 259
TF2_TYPE_RECIPE: int = 46
TF2_TYPE_SECONDARY_PDA: int = 49
TF2_TYPE_SECONDARY: int = 41
TF2_TYPE_SERVER_ENCHANTMENT: int = 47
TF2_TYPE_SPECIALIZED_KILLSTREAK_KIT: int = 235
TF2_TYPE_SPELLBOOK_PAGE: int = 302
TF2_TYPE_STRANGE_FILTER: int = 269
TF2_TYPE_STRANGE_PART: int = 226
TF2_TYPE_STRANGIFIER: int = 234
TF2_TYPE_SUPPLY_CRATE: int = 227
TF2_TYPE_TAUNT: int = 108
TF2_TYPE_TF_SPELLTOOL: int = 273
TF2_TYPE_TOOL: int = 222
TF2_TYPE_TYPE: int = 223
TF2_TYPE_UNLOCKED_CRATE: int = 257
TF2_TYPE_UNUSUALIFIER: int = 303
TF2_TYPE_USABLE_ITEM: int = 48
TF2_TYPE_WARPAINT: int = 321

# Классы (used_by)
TF2_CLASS_DEMOMAN: int = 33
TF2_CLASS_ENGINEER: int = 38
TF2_CLASS_HEAVY: int = 35
TF2_CLASS_MEDIC: int = 34
TF2_CLASS_PYRO: int = 36
TF2_CLASS_SCOUT: int = 30
TF2_CLASS_SNIPER: int = 31
TF2_CLASS_SOLDIER: int = 32
TF2_CLASS_SPY: int = 37

# Крафт/ковка
TF2_CRAFTABLE: int = 277
TF2_NOT_CRAFTABLE: int = 278

# DOTA2
# Редкости
DOTA2_RARITY_ANCIENT: int = 264
DOTA2_RARITY_ARCANA: int = 11
DOTA2_RARITY_COMMON: int = 2
DOTA2_RARITY_IMMORTAL: int = 20
DOTA2_RARITY_LEGENDARY: int = 13
DOTA2_RARITY_MYTHICAL: int = 9
DOTA2_RARITY_RARE: int = 5
DOTA2_RARITY_SEASONAL: int = 308
DOTA2_RARITY_UNCOMMON: int = 8

# Качества
DOTA2_QUALITY_ASCENDANT: int = 310
DOTA2_QUALITY_AUSPICIOUS: int = 124
DOTA2_QUALITY_AUTOGRAPHED: int = 219
DOTA2_QUALITY_BASE1: int = 266
DOTA2_QUALITY_BASE2: int = 288
DOTA2_QUALITY_CORRUPTED: int = 136
DOTA2_QUALITY_CURSED: int = 147
DOTA2_QUALITY_ELDER: int = 58
DOTA2_QUALITY_EXALTED: int = 109
DOTA2_QUALITY_FROZEN: int = 126
DOTA2_QUALITY_GENUINE: int = 25
DOTA2_QUALITY_GLITTER: int = 352
DOTA2_QUALITY_GOLD: int = 353
DOTA2_QUALITY_HEROIC: int = 185
DOTA2_QUALITY_HOLO: int = 354
DOTA2_QUALITY_INFUSED: int = 286
DOTA2_QUALITY_INSCRIBED: int = 10
DOTA2_QUALITY_LEGACY: int = 268
DOTA2_QUALITY_STANDARD: int = 1
DOTA2_QUALITY_UNUSUAL: int = 111

# Типы
DOTA2_TYPE_ANCIENT: int = 371
DOTA2_TYPE_ANNOUNCER: int = 116
DOTA2_TYPE_BASE: int = 258
DOTA2_TYPE_BUNDLE: int = 117
DOTA2_TYPE_COURIER: int = 18
DOTA2_TYPE_CURSORS_PACK: int = 15
DOTA2_TYPE_DIRE_TOWERS: int = 368
DOTA2_TYPE_EMBLEM: int = 357
DOTA2_TYPE_EMOTICON_TOOL: int = 287
DOTA2_TYPE_GEM_OR_RUNE: int = 16
DOTA2_TYPE_HUD_SKIN: int = 26
DOTA2_TYPE_LEAGUE: int = 241
DOTA2_TYPE_LOADING_SCREEN: int = 22
DOTA2_TYPE_MISC: int = 24
DOTA2_TYPE_MUSIC: int = 23
DOTA2_TYPE_PENNANT: int = 152
DOTA2_TYPE_PLAYER_CARD: int = 225
DOTA2_TYPE_RADIANT_TOWERS: int = 369
DOTA2_TYPE_RECIPE: int = 254
DOTA2_TYPE_RELIC: int = 320
DOTA2_TYPE_RETIRED_CHEST: int = 66
DOTA2_TYPE_STICKER: int = 351
DOTA2_TYPE_STICKER_CAPSULE: int = 355
DOTA2_TYPE_TAUNT: int = 14
DOTA2_TYPE_TERRAIN: int = 309
DOTA2_TYPE_TOOL: int = 3
DOTA2_TYPE_TREASURE: int = 112
DOTA2_TYPE_TREASURE_KEY: int = 247
DOTA2_TYPE_WARD: int = 150
DOTA2_TYPE_WEARABLE: int = 6

# Герои
# может позже

# SteamGift
# Регион
STEAMGIFT_REGION_ASIA: int = 251
STEAMGIFT_REGION_CHINA: int = 319
STEAMGIFT_REGION_GLOBAL: int = 73
STEAMGIFT_REGION_HONG_KONG_OR_TAIWAN: int = 300
STEAMGIFT_REGION_INDIA: int = 331
STEAMGIFT_REGION_MIDDLE_EAST: int = 356
STEAMGIFT_REGION_RUSSIA_CIS: int = 104
STEAMGIFT_REGION_SOUTH_AFRICA: int = 366
STEAMGIFT_REGION_SOUTH_AMERICA_OR_BRAZIL: int = 265
STEAMGIFT_REGION_TURKEY: int = 260

# Жанры
STEAMGIFT_GENRE_ACCOUNTING: int = 271
STEAMGIFT_GENRE_ACTION: int = 74
STEAMGIFT_GENRE_ADVENTURE: int = 97
STEAMGIFT_GENRE_ANIMATION_AND_MODELING: int = 270
STEAMGIFT_GENRE_AUDIO_PRODACTION: int = 242
STEAMGIFT_GENRE_CASUAL: int = 93
STEAMGIFT_GENRE_DESIGN_AND_ILLUSTRATION: int = 244
STEAMGIFT_GENRE_DECUMENTARY: int = 364
STEAMGIFT_GENRE_EARLY_ACCESS: int = 208
STEAMGIFT_GENRE_EDUCATION: int = 261
STEAMGIFT_GENRE_FREE_TO_PLAY: int = 105
STEAMGIFT_GENRE_GAME_DEVELOPMENT: int = 346
STEAMGIFT_GENRE_GORE: int = 305
STEAMGIFT_GENRE_INDIE: int = 75
STEAMGIFT_GENRE_MASSIVELY_MULTIPLAYER: int = 102
STEAMGIFT_GENRE_MOVIE: int = 363
STEAMGIFT_GENRE_NUDITY: int = 306
STEAMGIFT_GENRE_PHOTO_EDITING: int = 295
STEAMGIFT_GENRE_RPG: int = 89
STEAMGIFT_GENRE_RACING: int = 96
STEAMGIFT_GENRE_SEXUAL_CONTENT: int = 313
STEAMGIFT_GENRE_SIMULATION: int = 95
STEAMGIFT_GENRE_SOFTWARE_TRAINING: int = 262
STEAMGIFT_GENRE_SPORTS: int = 101
STEAMGIFT_GENRE_STRATEGY: int = 98
STEAMGIFT_GENRE_UTILITIES: int = 243
STEAMGIFT_GENRE_VIDEO_PRODACTION: int = 272
STEAMGIFT_GENRE_VIOLENT: int = 304
STEAMGIFT_GENRE_WEB_PUBLISHING: int = 245

# Mode
STEAMGIFT_MODE_ADDITIONAL_HIGH_QUALITY_AUDIO: int = 358
STEAMGIFT_MODE_CAPTIONS_AVAILABLE: int = 98
STEAMGIFT_MODE_CO_OP: int = 84
STEAMGIFT_MODE_OMMENTARY_AVAILABLE: int = 100
STEAMGIFT_MODE_CROSS_PLATFORM_MULTIPLAYER: int = 90
STEAMGIFT_MODE_DOWNLOADABLE_CONTENT: int = 87
STEAMGIFT_MODE_FAMILY_SHARING: int = 372
STEAMGIFT_MODE_FULL_CONTROLLER_SUPPORT: int = 94
STEAMGIFT_MODE_INAPP_PURCHASES: int = 291
STEAMGIFT_MODE_INCLUDES_SOURCE_SDK: int = 99
STEAMGIFT_MODE_INCLUDES_LEVEL_EDITOR: int = 92
STEAMGIFT_MODE_LAN_CO_OP: int = 330
STEAMGIFT_MODE_LAN_PVP: int = 329
STEAMGIFT_MODE_MMO: int = 103
STEAMGIFT_MODE_MULTIPLAYER: int = 76
STEAMGIFT_MODE_NATIVE_STEAM_CONTROLLER_SUPPORT: int = 284
STEAMGIFT_MODE_ONLINE_CO_OP: int = 292
STEAMGIFT_MODE_ONLINE_PVP: int = 294
STEAMGIFT_MODE_PARTIAL_CONTROLLER_SUPPORT: int = 79
STEAMGIFT_MODE_PVP: int = 324
STEAMGIFT_MODE_REMOTE_PLAY_TOGETHER: int = 328
STEAMGIFT_MODE_REMOTE_PLAY_ON_PHONE: int = 325
STEAMGIFT_MODE_REMOTE_PLAY_ON_TV: int = 327
STEAMGIFT_MODE_REMOTE_PLAY_ON_TABLET: int = 236
STEAMGIFT_MODE_SHARED_OR_SPLIT_SCREEN: int = 85
STEAMGIFT_MODE_SHARED_OR_SPLIT_SCREEN_CO_OP: int = 293
STEAMGIFT_MODE_SHARED_OR_SPLIT_SCREEN_PVP: int = 296
STEAMGIFT_MODE_SINGLEPLAYER: int = 83
STEAMGIFT_MODE_STATS: int = 82
STEAMGIFT_MODE_STEAM_ACHIVEMENTS: int = 77
STEAMGIFT_MODE_STEAM_CLOUD: int = 80
STEAMGIFT_MODE_STEAM_LEADERBOARDS: int = 86
STEAMGIFT_MODE_STEAM_TIMELINE: int = 374
STEAMGIFT_MODE_STEAM_TRADING_CARDS: int = 78
STEAMGIFT_MODE_STEAM_TURN_NOTIFICATIONS: int = 218
STEAMGIFT_MODE_STEAM_WORKSHOP1: int = 91
STEAMGIFT_MODE_STEAM_WORKSHOP2: int = 341
STEAMGIFT_MODE_STEAM_VR_COLLECTABLES: int = 343
STEAMGIFT_MODE_TRACKED_CONTROLLER_SUPPORT: int = 359
STEAMGIFT_MODE_VR_ONLY: int = 361
STEAMGIFT_MODE_VR_SUPPORT: int = 240
STEAMGIFT_MODE_VR_SUPPORTED: int = 360
STEAMGIFT_MODE_VALVE_ANTICHEAT_ENABLED: int = 81

# Обмен
STEAMGIFT_TRADABLE: int = 276
STEAMGIFT_NOT_TRADABLE: int = 281
